// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identity

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type IdentityUser struct {
	ID                uuid.UUID      `json:"id"`
	Email             string         `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	Status            string         `json:"status"`
	VerificationToken sql.NullString `json:"verification_token"`
	TokenExpiresAt    sql.NullTime   `json:"token_expires_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}
