// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identity

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type IdentityRefreshToken struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	TokenHash string         `json:"token_hash"`
	ExpiresAt time.Time      `json:"expires_at"`
	RevokedAt sql.NullTime   `json:"revoked_at"`
	CreatedAt time.Time      `json:"created_at"`
	UserAgent sql.NullString `json:"user_agent"`
	Ip        sql.NullString `json:"ip"`
}

type IdentityUser struct {
	ID                uuid.UUID      `json:"id"`
	Email             string         `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	Status            string         `json:"status"`
	VerificationToken sql.NullString `json:"verification_token"`
	TokenExpiresAt    sql.NullTime   `json:"token_expires_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}
