// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identity

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type IdentityUser struct {
	ID                uuid.UUID
	Email             string
	PasswordHash      string
	Status            string
	VerificationToken sql.NullString
	TokenExpiresAt    sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
