// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_token.sql

package identity

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO identity.refresh_tokens (user_id, token_hash, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at, user_agent, ip
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID      `json:"user_id"`
	TokenHash string         `json:"token_hash"`
	ExpiresAt time.Time      `json:"expires_at"`
	UserAgent sql.NullString `json:"user_agent"`
	Ip        sql.NullString `json:"ip"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (IdentityRefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i IdentityRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const findRefreshTokenByHash = `-- name: FindRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, revoked_at, created_at, user_agent, ip FROM identity.refresh_tokens WHERE token_hash = $1
`

func (q *Queries) FindRefreshTokenByHash(ctx context.Context, tokenHash string) (IdentityRefreshToken, error) {
	row := q.db.QueryRowContext(ctx, findRefreshTokenByHash, tokenHash)
	var i IdentityRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE identity.refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE identity.refresh_tokens
SET revoked_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at, user_agent, ip
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) (IdentityRefreshToken, error) {
	row := q.db.QueryRowContext(ctx, revokeRefreshToken, id)
	var i IdentityRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}
