// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package identity

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO identity.users (email, password_hash, status, verification_token, token_expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, status, verification_token, token_expires_at, created_at, updated_at
`

type CreateUserParams struct {
	Email             string         `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	Status            string         `json:"status"`
	VerificationToken sql.NullString `json:"verification_token"`
	TokenExpiresAt    sql.NullTime   `json:"token_expires_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (IdentityUser, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
		arg.VerificationToken,
		arg.TokenExpiresAt,
	)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.VerificationToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findByEmail = `-- name: FindByEmail :one
SELECT id, email, password_hash, status, verification_token, token_expires_at, created_at, updated_at FROM identity.users WHERE email = $1
`

func (q *Queries) FindByEmail(ctx context.Context, email string) (IdentityUser, error) {
	row := q.db.QueryRowContext(ctx, findByEmail, email)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.VerificationToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findByVerificationToken = `-- name: FindByVerificationToken :one
SELECT id, email, password_hash, status, verification_token, token_expires_at, created_at, updated_at FROM identity.users WHERE verification_token = $1::text AND token_expires_at > NOW()
`

func (q *Queries) FindByVerificationToken(ctx context.Context, dollar_1 string) (IdentityUser, error) {
	row := q.db.QueryRowContext(ctx, findByVerificationToken, dollar_1)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.VerificationToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, password_hash, status, verification_token, token_expires_at, created_at, updated_at FROM identity.users WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (IdentityUser, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.VerificationToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE identity.users
SET status = $2, verification_token = NULL, token_expires_at = NULL, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, status, verification_token, token_expires_at, created_at, updated_at
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (IdentityUser, error) {
	row := q.db.QueryRowContext(ctx, updateUserStatus, arg.ID, arg.Status)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.VerificationToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
