services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: main_db  # общая база
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Сюда можно положить entrypoint-скрипт, который создаёт схемы и пользователей
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  identity:
    build: ./cmd/identity
    environment:
      # identity_user имеет доступ ТОЛЬКО к схеме identity
      DATABASE_URL: postgresql://identity_user:pass@postgres:5432/main_db?search_path=identity&sslmode=disable
      SMTP_SERVER: smtp.yandex.ru:465
      # ... остальные переменные
    depends_on:
      - postgres

  lidar:
    build: ./cmd/lidar
    environment:
      # lidar_user имеет доступ ТОЛЬКО к схеме public
      DATABASE_URL: postgresql://lidar_user:pass@postgres:5432/main_db?search_path=public&sslmode=disable
    depends_on:
      - postgres

volumes:
  pgdata:
