// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: atmosphere.sql

package lidar

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createAtmosphereProfile = `-- name: CreateAtmosphereProfile :one
INSERT INTO lidar.atmosphere_profiles (experiment_id, altitude, temperature, pressure)
VALUES ($1, $2, $3, $4)
RETURNING id, altitude, temperature, pressure, created_at, experiment_id
`

type CreateAtmosphereProfileParams struct {
	ExperimentID uuid.UUID `json:"experiment_id"`
	Altitude     []float64 `json:"altitude"`
	Temperature  []float64 `json:"temperature"`
	Pressure     []float64 `json:"pressure"`
}

// Atmosphere Profiles
func (q *Queries) CreateAtmosphereProfile(ctx context.Context, arg CreateAtmosphereProfileParams) (LidarAtmosphereProfile, error) {
	row := q.db.QueryRowContext(ctx, createAtmosphereProfile,
		arg.ExperimentID,
		pq.Array(arg.Altitude),
		pq.Array(arg.Temperature),
		pq.Array(arg.Pressure),
	)
	var i LidarAtmosphereProfile
	err := row.Scan(
		&i.ID,
		pq.Array(&i.Altitude),
		pq.Array(&i.Temperature),
		pq.Array(&i.Pressure),
		&i.CreatedAt,
		&i.ExperimentID,
	)
	return i, err
}

const deleteAtmosphereProfile = `-- name: DeleteAtmosphereProfile :exec
DELETE FROM lidar.atmosphere_profiles WHERE id = $1
`

func (q *Queries) DeleteAtmosphereProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAtmosphereProfile, id)
	return err
}

const getAtmosphereProfileByID = `-- name: GetAtmosphereProfileByID :one
SELECT id, altitude, temperature, pressure, created_at, experiment_id FROM lidar.atmosphere_profiles WHERE id = $1
`

func (q *Queries) GetAtmosphereProfileByID(ctx context.Context, id uuid.UUID) (LidarAtmosphereProfile, error) {
	row := q.db.QueryRowContext(ctx, getAtmosphereProfileByID, id)
	var i LidarAtmosphereProfile
	err := row.Scan(
		&i.ID,
		pq.Array(&i.Altitude),
		pq.Array(&i.Temperature),
		pq.Array(&i.Pressure),
		&i.CreatedAt,
		&i.ExperimentID,
	)
	return i, err
}

const listAtmosphereProfiles = `-- name: ListAtmosphereProfiles :many
SELECT id, altitude, temperature, pressure, created_at, experiment_id FROM lidar.atmosphere_profiles
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAtmosphereProfilesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAtmosphereProfiles(ctx context.Context, arg ListAtmosphereProfilesParams) ([]LidarAtmosphereProfile, error) {
	rows, err := q.db.QueryContext(ctx, listAtmosphereProfiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LidarAtmosphereProfile
	for rows.Next() {
		var i LidarAtmosphereProfile
		if err := rows.Scan(
			&i.ID,
			pq.Array(&i.Altitude),
			pq.Array(&i.Temperature),
			pq.Array(&i.Pressure),
			&i.CreatedAt,
			&i.ExperimentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
