// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: licelfile.sql

package lidar

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLicelFile = `-- name: CreateLicelFile :one
INSERT INTO lidar.licelfiles (
    experiment_id, measurement_start, measurement_stop,
    n_datasets, laser_freq, is_background, raw_storage_id, filename
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, experiment_id, measurement_start, measurement_stop, n_datasets, laser_freq, is_background, raw_storage_id, filename, created_at, deleted_at
`

type CreateLicelFileParams struct {
	ExperimentID     uuid.UUID `json:"experiment_id"`
	MeasurementStart time.Time `json:"measurement_start"`
	MeasurementStop  time.Time `json:"measurement_stop"`
	NDatasets        int32     `json:"n_datasets"`
	LaserFreq        int32     `json:"laser_freq"`
	IsBackground     bool      `json:"is_background"`
	RawStorageID     uuid.UUID `json:"raw_storage_id"`
	Filename         string    `json:"filename"`
}

func (q *Queries) CreateLicelFile(ctx context.Context, arg CreateLicelFileParams) (LidarLicelfile, error) {
	row := q.db.QueryRowContext(ctx, createLicelFile,
		arg.ExperimentID,
		arg.MeasurementStart,
		arg.MeasurementStop,
		arg.NDatasets,
		arg.LaserFreq,
		arg.IsBackground,
		arg.RawStorageID,
		arg.Filename,
	)
	var i LidarLicelfile
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.MeasurementStart,
		&i.MeasurementStop,
		&i.NDatasets,
		&i.LaserFreq,
		&i.IsBackground,
		&i.RawStorageID,
		&i.Filename,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLicelFileByID = `-- name: GetLicelFileByID :one
SELECT id, experiment_id, measurement_start, measurement_stop, n_datasets, laser_freq, is_background, raw_storage_id, filename, created_at, deleted_at FROM lidar.licelfiles WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLicelFileByID(ctx context.Context, id uuid.UUID) (LidarLicelfile, error) {
	row := q.db.QueryRowContext(ctx, getLicelFileByID, id)
	var i LidarLicelfile
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.MeasurementStart,
		&i.MeasurementStop,
		&i.NDatasets,
		&i.LaserFreq,
		&i.IsBackground,
		&i.RawStorageID,
		&i.Filename,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listLicelFilesByExperiment = `-- name: ListLicelFilesByExperiment :many
SELECT id, experiment_id, measurement_start, measurement_stop, n_datasets, laser_freq, is_background, raw_storage_id, filename, created_at, deleted_at FROM lidar.licelfiles
WHERE experiment_id = $1 AND deleted_at IS NULL
ORDER BY measurement_start ASC
`

func (q *Queries) ListLicelFilesByExperiment(ctx context.Context, experimentID uuid.UUID) ([]LidarLicelfile, error) {
	rows, err := q.db.QueryContext(ctx, listLicelFilesByExperiment, experimentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LidarLicelfile
	for rows.Next() {
		var i LidarLicelfile
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.MeasurementStart,
			&i.MeasurementStop,
			&i.NDatasets,
			&i.LaserFreq,
			&i.IsBackground,
			&i.RawStorageID,
			&i.Filename,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreLicelFile = `-- name: RestoreLicelFile :one
UPDATE lidar.licelfiles SET deleted_at = NULL WHERE id = $1
RETURNING id, experiment_id, measurement_start, measurement_stop, n_datasets, laser_freq, is_background, raw_storage_id, filename, created_at, deleted_at
`

func (q *Queries) RestoreLicelFile(ctx context.Context, id uuid.UUID) (LidarLicelfile, error) {
	row := q.db.QueryRowContext(ctx, restoreLicelFile, id)
	var i LidarLicelfile
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.MeasurementStart,
		&i.MeasurementStop,
		&i.NDatasets,
		&i.LaserFreq,
		&i.IsBackground,
		&i.RawStorageID,
		&i.Filename,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteLicelFile = `-- name: SoftDeleteLicelFile :exec
UPDATE lidar.licelfiles SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteLicelFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteLicelFile, id)
	return err
}
