// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: licelprofile.sql

package lidar

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createLicelProfile = `-- name: CreateLicelProfile :one
INSERT INTO lidar.licel_profiles (
    licelfile_id, n_data_points, high_voltage, bin_width,
    wavelength, polarization, device_id,
    n_shots, discr_level, data
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, licelfile_id, n_data_points, high_voltage, bin_width, wavelength, polarization, device_id, n_shots, discr_level, data, created_at, updated_at, deleted_at
`

type CreateLicelProfileParams struct {
	LicelfileID  uuid.UUID `json:"licelfile_id"`
	NDataPoints  int32     `json:"n_data_points"`
	HighVoltage  float32   `json:"high_voltage"`
	BinWidth     float32   `json:"bin_width"`
	Wavelength   float32   `json:"wavelength"`
	Polarization string    `json:"polarization"`
	DeviceID     string    `json:"device_id"`
	NShots       int32     `json:"n_shots"`
	DiscrLevel   float32   `json:"discr_level"`
	Data         []float64 `json:"data"`
}

func (q *Queries) CreateLicelProfile(ctx context.Context, arg CreateLicelProfileParams) (LidarLicelProfile, error) {
	row := q.db.QueryRowContext(ctx, createLicelProfile,
		arg.LicelfileID,
		arg.NDataPoints,
		arg.HighVoltage,
		arg.BinWidth,
		arg.Wavelength,
		arg.Polarization,
		arg.DeviceID,
		arg.NShots,
		arg.DiscrLevel,
		pq.Array(arg.Data),
	)
	var i LidarLicelProfile
	err := row.Scan(
		&i.ID,
		&i.LicelfileID,
		&i.NDataPoints,
		&i.HighVoltage,
		&i.BinWidth,
		&i.Wavelength,
		&i.Polarization,
		&i.DeviceID,
		&i.NShots,
		&i.DiscrLevel,
		pq.Array(&i.Data),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findProfilesWithBackgroundByExperiment = `-- name: FindProfilesWithBackgroundByExperiment :many
WITH background_profiles AS (
    SELECT
        lf.experiment_id,
        lp.device_id,
        lp.wavelength,
        lp.polarization,
        lp.id AS bg_profile_id,
        lp.data AS bg_data,
        lp.n_data_points AS bg_points,
        lp.licelfile_id AS bg_licelfile_id,
        lp.bin_width AS bg_bin_width
    FROM lidar.licelfiles lf
    INNER JOIN lidar.licel_profiles lp ON lp.licelfile_id = lf.id
    WHERE lf.experiment_id = $1
        AND lf.is_background = true
        AND lf.deleted_at IS NULL
        AND lp.deleted_at IS NULL
        AND array_length(lp.data, 1) > 0
),
signal_profiles AS (
    SELECT
        lf.experiment_id,
        lp.device_id,
        lp.wavelength,
        lp.polarization,
        lp.id AS signal_profile_id,
        lp.data AS signal_data,
        lp.n_data_points AS signal_points,
        lp.licelfile_id AS signal_licelfile_id,
        lp.bin_width AS signal_bin_width
    FROM lidar.licelfiles lf
    INNER JOIN lidar.licel_profiles lp ON lp.licelfile_id = lf.id
    WHERE lf.experiment_id = $1
        AND lf.is_background = false
        AND lf.deleted_at IS NULL
        AND lp.deleted_at IS NULL
        AND array_length(lp.data, 1) > 0
)
SELECT
    s.experiment_id,
    s.signal_profile_id,
    s.device_id,
    s.wavelength,
    s.polarization,
    s.signal_data,
    s.signal_points,
    s.signal_licelfile_id,
    s.signal_bin_width,
    b.bg_profile_id,
    b.bg_data,
    b.bg_points,
    b.bg_licelfile_id,
    b.bg_bin_width,
    CASE
        WHEN b.bg_profile_id IS NULL THEN 'NO_BACKGROUND'
        WHEN s.signal_points = b.bg_points THEN 'OK'
        ELSE 'MISMATCH'
    END AS data_length_match
FROM signal_profiles s
LEFT JOIN background_profiles b
    ON s.experiment_id = b.experiment_id
    AND s.device_id = b.device_id
    AND s.wavelength = b.wavelength
    AND s.polarization = b.polarization
ORDER BY s.device_id, s.wavelength, s.polarization
`

type FindProfilesWithBackgroundByExperimentRow struct {
	ExperimentID      uuid.UUID       `json:"experiment_id"`
	SignalProfileID   uuid.UUID       `json:"signal_profile_id"`
	DeviceID          string          `json:"device_id"`
	Wavelength        float32         `json:"wavelength"`
	Polarization      string          `json:"polarization"`
	SignalData        []float64       `json:"signal_data"`
	SignalPoints      int32           `json:"signal_points"`
	SignalLicelfileID uuid.UUID       `json:"signal_licelfile_id"`
	SignalBinWidth    float32         `json:"signal_bin_width"`
	BgProfileID       uuid.NullUUID   `json:"bg_profile_id"`
	BgData            []float64       `json:"bg_data"`
	BgPoints          sql.NullInt32   `json:"bg_points"`
	BgLicelfileID     uuid.NullUUID   `json:"bg_licelfile_id"`
	BgBinWidth        sql.NullFloat64 `json:"bg_bin_width"`
	DataLengthMatch   string          `json:"data_length_match"`
}

func (q *Queries) FindProfilesWithBackgroundByExperiment(ctx context.Context, experimentID uuid.UUID) ([]FindProfilesWithBackgroundByExperimentRow, error) {
	rows, err := q.db.QueryContext(ctx, findProfilesWithBackgroundByExperiment, experimentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindProfilesWithBackgroundByExperimentRow
	for rows.Next() {
		var i FindProfilesWithBackgroundByExperimentRow
		if err := rows.Scan(
			&i.ExperimentID,
			&i.SignalProfileID,
			&i.DeviceID,
			&i.Wavelength,
			&i.Polarization,
			pq.Array(&i.SignalData),
			&i.SignalPoints,
			&i.SignalLicelfileID,
			&i.SignalBinWidth,
			&i.BgProfileID,
			pq.Array(&i.BgData),
			&i.BgPoints,
			&i.BgLicelfileID,
			&i.BgBinWidth,
			&i.DataLengthMatch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLicelProfileByID = `-- name: GetLicelProfileByID :one
SELECT id, licelfile_id, n_data_points, high_voltage, bin_width, wavelength, polarization, device_id, n_shots, discr_level, data, created_at, updated_at, deleted_at FROM lidar.licel_profiles WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLicelProfileByID(ctx context.Context, id uuid.UUID) (LidarLicelProfile, error) {
	row := q.db.QueryRowContext(ctx, getLicelProfileByID, id)
	var i LidarLicelProfile
	err := row.Scan(
		&i.ID,
		&i.LicelfileID,
		&i.NDataPoints,
		&i.HighVoltage,
		&i.BinWidth,
		&i.Wavelength,
		&i.Polarization,
		&i.DeviceID,
		&i.NShots,
		&i.DiscrLevel,
		pq.Array(&i.Data),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBackgroundProfilesByExperiment = `-- name: ListBackgroundProfilesByExperiment :many
SELECT lp.id, lp.licelfile_id, lp.n_data_points, lp.high_voltage, lp.bin_width,
       lp.wavelength, lp.polarization, lp.device_id, lp.n_shots, lp.discr_level,
       lp.data, lp.created_at, lp.updated_at, lp.deleted_at
FROM lidar.licel_profiles lp
JOIN lidar.licelfiles lf ON lf.id = lp.licelfile_id
WHERE lf.experiment_id = $1
  AND lf.is_background = TRUE
  AND lp.deleted_at IS NULL
  AND lf.deleted_at IS NULL
ORDER BY lp.wavelength, lp.polarization
`

func (q *Queries) ListBackgroundProfilesByExperiment(ctx context.Context, experimentID uuid.UUID) ([]LidarLicelProfile, error) {
	rows, err := q.db.QueryContext(ctx, listBackgroundProfilesByExperiment, experimentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LidarLicelProfile
	for rows.Next() {
		var i LidarLicelProfile
		if err := rows.Scan(
			&i.ID,
			&i.LicelfileID,
			&i.NDataPoints,
			&i.HighVoltage,
			&i.BinWidth,
			&i.Wavelength,
			&i.Polarization,
			&i.DeviceID,
			&i.NShots,
			&i.DiscrLevel,
			pq.Array(&i.Data),
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLicelProfilesByLicelFile = `-- name: ListLicelProfilesByLicelFile :many
SELECT id, licelfile_id, n_data_points, high_voltage, bin_width, wavelength, polarization, device_id, n_shots, discr_level, data, created_at, updated_at, deleted_at FROM lidar.licel_profiles
WHERE licelfile_id = $1 AND deleted_at IS NULL
ORDER BY wavelength, polarization
`

func (q *Queries) ListLicelProfilesByLicelFile(ctx context.Context, licelfileID uuid.UUID) ([]LidarLicelProfile, error) {
	rows, err := q.db.QueryContext(ctx, listLicelProfilesByLicelFile, licelfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LidarLicelProfile
	for rows.Next() {
		var i LidarLicelProfile
		if err := rows.Scan(
			&i.ID,
			&i.LicelfileID,
			&i.NDataPoints,
			&i.HighVoltage,
			&i.BinWidth,
			&i.Wavelength,
			&i.Polarization,
			&i.DeviceID,
			&i.NShots,
			&i.DiscrLevel,
			pq.Array(&i.Data),
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreLicelProfile = `-- name: RestoreLicelProfile :one
UPDATE lidar.licel_profiles SET deleted_at = NULL, updated_at = now() WHERE id = $1
RETURNING id, licelfile_id, n_data_points, high_voltage, bin_width, wavelength, polarization, device_id, n_shots, discr_level, data, created_at, updated_at, deleted_at
`

func (q *Queries) RestoreLicelProfile(ctx context.Context, id uuid.UUID) (LidarLicelProfile, error) {
	row := q.db.QueryRowContext(ctx, restoreLicelProfile, id)
	var i LidarLicelProfile
	err := row.Scan(
		&i.ID,
		&i.LicelfileID,
		&i.NDataPoints,
		&i.HighVoltage,
		&i.BinWidth,
		&i.Wavelength,
		&i.Polarization,
		&i.DeviceID,
		&i.NShots,
		&i.DiscrLevel,
		pq.Array(&i.Data),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteLicelProfile = `-- name: SoftDeleteLicelProfile :exec
UPDATE lidar.licel_profiles SET deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteLicelProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteLicelProfile, id)
	return err
}
