// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prepared.sql

package lidar

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createPreparedMeta = `-- name: CreatePreparedMeta :one
INSERT INTO lidar.prepared_meta (
    experiment_id, background_type, background_from, trim_from
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, experiment_id, background_type, background_from, trim_from
`

type CreatePreparedMetaParams struct {
	ExperimentID   uuid.UUID `json:"experiment_id"`
	BackgroundType string    `json:"background_type"`
	BackgroundFrom float32   `json:"background_from"`
	TrimFrom       float32   `json:"trim_from"`
}

func (q *Queries) CreatePreparedMeta(ctx context.Context, arg CreatePreparedMetaParams) (LidarPreparedMetum, error) {
	row := q.db.QueryRowContext(ctx, createPreparedMeta,
		arg.ExperimentID,
		arg.BackgroundType,
		arg.BackgroundFrom,
		arg.TrimFrom,
	)
	var i LidarPreparedMetum
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.BackgroundType,
		&i.BackgroundFrom,
		&i.TrimFrom,
	)
	return i, err
}

const createPreparedProfile = `-- name: CreatePreparedProfile :one
INSERT INTO lidar.prepared_profiles (
    prepared_meta_id, licel_profile_id, data
) VALUES (
    $1, $2, $3
)
RETURNING id, prepared_meta_id, licel_profile_id, data, created_at, updated_at, deleted_at
`

type CreatePreparedProfileParams struct {
	PreparedMetaID uuid.UUID `json:"prepared_meta_id"`
	LicelProfileID uuid.UUID `json:"licel_profile_id"`
	Data           []float32 `json:"data"`
}

func (q *Queries) CreatePreparedProfile(ctx context.Context, arg CreatePreparedProfileParams) (LidarPreparedProfile, error) {
	row := q.db.QueryRowContext(ctx, createPreparedProfile, arg.PreparedMetaID, arg.LicelProfileID, pq.Array(arg.Data))
	var i LidarPreparedProfile
	err := row.Scan(
		&i.ID,
		&i.PreparedMetaID,
		&i.LicelProfileID,
		pq.Array(&i.Data),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPreparedMetaByExperimentID = `-- name: GetPreparedMetaByExperimentID :one
SELECT id, experiment_id, background_type, background_from, trim_from FROM lidar.prepared_meta WHERE experiment_id = $1
`

func (q *Queries) GetPreparedMetaByExperimentID(ctx context.Context, experimentID uuid.UUID) (LidarPreparedMetum, error) {
	row := q.db.QueryRowContext(ctx, getPreparedMetaByExperimentID, experimentID)
	var i LidarPreparedMetum
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.BackgroundType,
		&i.BackgroundFrom,
		&i.TrimFrom,
	)
	return i, err
}

const listPreparedProfilesByMetaID = `-- name: ListPreparedProfilesByMetaID :many
SELECT id, prepared_meta_id, licel_profile_id, data, created_at, updated_at, deleted_at FROM lidar.prepared_profiles
WHERE prepared_meta_id = $1 AND deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListPreparedProfilesByMetaID(ctx context.Context, preparedMetaID uuid.UUID) ([]LidarPreparedProfile, error) {
	rows, err := q.db.QueryContext(ctx, listPreparedProfilesByMetaID, preparedMetaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LidarPreparedProfile
	for rows.Next() {
		var i LidarPreparedProfile
		if err := rows.Scan(
			&i.ID,
			&i.PreparedMetaID,
			&i.LicelProfileID,
			pq.Array(&i.Data),
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
