// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prepared.sql

package lidar

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createPreparedMeta = `-- name: CreatePreparedMeta :one
INSERT INTO lidar.prepared_meta (
    experiment_id, background_type, background_from, trim_from
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, experiment_id, background_type, background_from, trim_from
`

type CreatePreparedMetaParams struct {
	ExperimentID   uuid.UUID `json:"experiment_id"`
	BackgroundType string    `json:"background_type"`
	BackgroundFrom float32   `json:"background_from"`
	TrimFrom       float32   `json:"trim_from"`
}

func (q *Queries) CreatePreparedMeta(ctx context.Context, arg CreatePreparedMetaParams) (LidarPreparedMetum, error) {
	row := q.db.QueryRowContext(ctx, createPreparedMeta,
		arg.ExperimentID,
		arg.BackgroundType,
		arg.BackgroundFrom,
		arg.TrimFrom,
	)
	var i LidarPreparedMetum
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.BackgroundType,
		&i.BackgroundFrom,
		&i.TrimFrom,
	)
	return i, err
}

const createPreparedProfile = `-- name: CreatePreparedProfile :one
INSERT INTO lidar.prepared_profiles (
    prepared_meta_id, licel_profile_id, data
) VALUES (
    $1, $2, $3
)
RETURNING id, prepared_meta_id, licel_profile_id, data, created_at, updated_at, deleted_at
`

type CreatePreparedProfileParams struct {
	PreparedMetaID uuid.UUID `json:"prepared_meta_id"`
	LicelProfileID uuid.UUID `json:"licel_profile_id"`
	Data           []float32 `json:"data"`
}

func (q *Queries) CreatePreparedProfile(ctx context.Context, arg CreatePreparedProfileParams) (LidarPreparedProfile, error) {
	row := q.db.QueryRowContext(ctx, createPreparedProfile, arg.PreparedMetaID, arg.LicelProfileID, pq.Array(arg.Data))
	var i LidarPreparedProfile
	err := row.Scan(
		&i.ID,
		&i.PreparedMetaID,
		&i.LicelProfileID,
		pq.Array(&i.Data),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPreparedMetaByExperimentID = `-- name: GetPreparedMetaByExperimentID :one
SELECT id, experiment_id, background_type, background_from, trim_from FROM lidar.prepared_meta WHERE experiment_id = $1
`

func (q *Queries) GetPreparedMetaByExperimentID(ctx context.Context, experimentID uuid.UUID) (LidarPreparedMetum, error) {
	row := q.db.QueryRowContext(ctx, getPreparedMetaByExperimentID, experimentID)
	var i LidarPreparedMetum
	err := row.Scan(
		&i.ID,
		&i.ExperimentID,
		&i.BackgroundType,
		&i.BackgroundFrom,
		&i.TrimFrom,
	)
	return i, err
}

const listPreparedExperiments = `-- name: ListPreparedExperiments :many
SELECT DISTINCT pm.experiment_id
FROM lidar.prepared_profiles pp
JOIN lidar.prepared_meta pm ON pm.id = pp.prepared_meta_id
WHERE pp.deleted_at IS NULL
ORDER BY pm.experiment_id
`

func (q *Queries) ListPreparedExperiments(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listPreparedExperiments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var experiment_id uuid.UUID
		if err := rows.Scan(&experiment_id); err != nil {
			return nil, err
		}
		items = append(items, experiment_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreparedProfileDeviceIDs = `-- name: ListPreparedProfileDeviceIDs :many
SELECT DISTINCT lp.device_id
FROM lidar.prepared_profiles pp
JOIN lidar.prepared_meta pm ON pm.id = pp.prepared_meta_id
JOIN lidar.licel_profiles lp ON lp.id = pp.licel_profile_id
WHERE pm.experiment_id = $1 AND pp.deleted_at IS NULL
  AND ($2::real IS NULL OR lp.wavelength = $2)
  AND ($3::text IS NULL OR lp.polarization = $3)
ORDER BY lp.device_id
`

type ListPreparedProfileDeviceIDsParams struct {
	ExperimentID uuid.UUID       `json:"experiment_id"`
	Wavelength   sql.NullFloat64 `json:"wavelength"`
	Polarization sql.NullString  `json:"polarization"`
}

func (q *Queries) ListPreparedProfileDeviceIDs(ctx context.Context, arg ListPreparedProfileDeviceIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPreparedProfileDeviceIDs, arg.ExperimentID, arg.Wavelength, arg.Polarization)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var device_id string
		if err := rows.Scan(&device_id); err != nil {
			return nil, err
		}
		items = append(items, device_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreparedProfilePolarizations = `-- name: ListPreparedProfilePolarizations :many
SELECT DISTINCT lp.polarization
FROM lidar.prepared_profiles pp
JOIN lidar.prepared_meta pm ON pm.id = pp.prepared_meta_id
JOIN lidar.licel_profiles lp ON lp.id = pp.licel_profile_id
WHERE pm.experiment_id = $1 AND pp.deleted_at IS NULL
  AND ($2::real IS NULL OR lp.wavelength = $2)
ORDER BY lp.polarization
`

type ListPreparedProfilePolarizationsParams struct {
	ExperimentID uuid.UUID       `json:"experiment_id"`
	Wavelength   sql.NullFloat64 `json:"wavelength"`
}

func (q *Queries) ListPreparedProfilePolarizations(ctx context.Context, arg ListPreparedProfilePolarizationsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPreparedProfilePolarizations, arg.ExperimentID, arg.Wavelength)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var polarization string
		if err := rows.Scan(&polarization); err != nil {
			return nil, err
		}
		items = append(items, polarization)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreparedProfileWavelengths = `-- name: ListPreparedProfileWavelengths :many
SELECT DISTINCT lp.wavelength
FROM lidar.prepared_profiles pp
JOIN lidar.prepared_meta pm ON pm.id = pp.prepared_meta_id
JOIN lidar.licel_profiles lp ON lp.id = pp.licel_profile_id
WHERE pm.experiment_id = $1 AND pp.deleted_at IS NULL
ORDER BY lp.wavelength
`

func (q *Queries) ListPreparedProfileWavelengths(ctx context.Context, experimentID uuid.UUID) ([]float32, error) {
	rows, err := q.db.QueryContext(ctx, listPreparedProfileWavelengths, experimentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []float32
	for rows.Next() {
		var wavelength float32
		if err := rows.Scan(&wavelength); err != nil {
			return nil, err
		}
		items = append(items, wavelength)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreparedProfilesByExperiment = `-- name: ListPreparedProfilesByExperiment :many
SELECT
    pp.id,
    pp.data,
    pp.created_at,
    lp.wavelength,
    lp.polarization,
    lp.device_id,
    lp.bin_width,
    lf.measurement_start,
    pm.background_type,
    pm.background_from,
    pm.trim_from
FROM lidar.prepared_profiles pp
JOIN lidar.prepared_meta pm ON pm.id = pp.prepared_meta_id
JOIN lidar.licel_profiles lp ON lp.id = pp.licel_profile_id
JOIN lidar.licelfiles lf ON lf.id = lp.licelfile_id
WHERE pm.experiment_id = $1
  AND pp.deleted_at IS NULL
  AND ($2::real IS NULL OR lp.wavelength = $2)
  AND ($3::text IS NULL OR lp.polarization = $3)
  AND ($4::text IS NULL OR lp.device_id = $4)
ORDER BY lp.wavelength, lp.polarization, lp.device_id
`

type ListPreparedProfilesByExperimentParams struct {
	ExperimentID uuid.UUID       `json:"experiment_id"`
	Wavelength   sql.NullFloat64 `json:"wavelength"`
	Polarization sql.NullString  `json:"polarization"`
	DeviceID     sql.NullString  `json:"device_id"`
}

type ListPreparedProfilesByExperimentRow struct {
	ID               uuid.UUID `json:"id"`
	Data             []float32 `json:"data"`
	CreatedAt        time.Time `json:"created_at"`
	Wavelength       float32   `json:"wavelength"`
	Polarization     string    `json:"polarization"`
	DeviceID         string    `json:"device_id"`
	BinWidth         float32   `json:"bin_width"`
	MeasurementStart time.Time `json:"measurement_start"`
	BackgroundType   string    `json:"background_type"`
	BackgroundFrom   float32   `json:"background_from"`
	TrimFrom         float32   `json:"trim_from"`
}

func (q *Queries) ListPreparedProfilesByExperiment(ctx context.Context, arg ListPreparedProfilesByExperimentParams) ([]ListPreparedProfilesByExperimentRow, error) {
	rows, err := q.db.QueryContext(ctx, listPreparedProfilesByExperiment,
		arg.ExperimentID,
		arg.Wavelength,
		arg.Polarization,
		arg.DeviceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPreparedProfilesByExperimentRow
	for rows.Next() {
		var i ListPreparedProfilesByExperimentRow
		if err := rows.Scan(
			&i.ID,
			pq.Array(&i.Data),
			&i.CreatedAt,
			&i.Wavelength,
			&i.Polarization,
			&i.DeviceID,
			&i.BinWidth,
			&i.MeasurementStart,
			&i.BackgroundType,
			&i.BackgroundFrom,
			&i.TrimFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreparedProfilesByMetaID = `-- name: ListPreparedProfilesByMetaID :many
SELECT id, prepared_meta_id, licel_profile_id, data, created_at, updated_at, deleted_at FROM lidar.prepared_profiles
WHERE prepared_meta_id = $1 AND deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListPreparedProfilesByMetaID(ctx context.Context, preparedMetaID uuid.UUID) ([]LidarPreparedProfile, error) {
	rows, err := q.db.QueryContext(ctx, listPreparedProfilesByMetaID, preparedMetaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LidarPreparedProfile
	for rows.Next() {
		var i LidarPreparedProfile
		if err := rows.Scan(
			&i.ID,
			&i.PreparedMetaID,
			&i.LicelProfileID,
			pq.Array(&i.Data),
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
