// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage_objects.sql

package lidar

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createStorageObject = `-- name: CreateStorageObject :one
INSERT INTO lidar.storage_objects (bucket, path, size_bytes, etag, content_type, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, bucket, path, size_bytes, etag, content_type, metadata, created_at
`

type CreateStorageObjectParams struct {
	Bucket      string                `json:"bucket"`
	Path        string                `json:"path"`
	SizeBytes   sql.NullInt64         `json:"size_bytes"`
	Etag        sql.NullString        `json:"etag"`
	ContentType sql.NullString        `json:"content_type"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
}

// Storage Objects
func (q *Queries) CreateStorageObject(ctx context.Context, arg CreateStorageObjectParams) (LidarStorageObject, error) {
	row := q.db.QueryRowContext(ctx, createStorageObject,
		arg.Bucket,
		arg.Path,
		arg.SizeBytes,
		arg.Etag,
		arg.ContentType,
		arg.Metadata,
	)
	var i LidarStorageObject
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.Path,
		&i.SizeBytes,
		&i.Etag,
		&i.ContentType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStorageObject = `-- name: DeleteStorageObject :exec
DELETE FROM lidar.storage_objects WHERE id = $1
`

func (q *Queries) DeleteStorageObject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStorageObject, id)
	return err
}

const getStorageObjectByBucketPath = `-- name: GetStorageObjectByBucketPath :one
SELECT id, bucket, path, size_bytes, etag, content_type, metadata, created_at FROM lidar.storage_objects WHERE bucket = $1 AND path = $2
`

type GetStorageObjectByBucketPathParams struct {
	Bucket string `json:"bucket"`
	Path   string `json:"path"`
}

func (q *Queries) GetStorageObjectByBucketPath(ctx context.Context, arg GetStorageObjectByBucketPathParams) (LidarStorageObject, error) {
	row := q.db.QueryRowContext(ctx, getStorageObjectByBucketPath, arg.Bucket, arg.Path)
	var i LidarStorageObject
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.Path,
		&i.SizeBytes,
		&i.Etag,
		&i.ContentType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getStorageObjectByID = `-- name: GetStorageObjectByID :one
SELECT id, bucket, path, size_bytes, etag, content_type, metadata, created_at FROM lidar.storage_objects WHERE id = $1
`

func (q *Queries) GetStorageObjectByID(ctx context.Context, id uuid.UUID) (LidarStorageObject, error) {
	row := q.db.QueryRowContext(ctx, getStorageObjectByID, id)
	var i LidarStorageObject
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.Path,
		&i.SizeBytes,
		&i.Etag,
		&i.ContentType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
