// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_status.sql

package lidar

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createTaskStatus = `-- name: CreateTaskStatus :one
INSERT INTO lidar.task_statuses (
    id, subject, status, task_params
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, subject, status, task_params, error_message, created_at, updated_at, started_at, finished_at
`

type CreateTaskStatusParams struct {
	ID         uuid.UUID       `json:"id"`
	Subject    string          `json:"subject"`
	Status     string          `json:"status"`
	TaskParams json.RawMessage `json:"task_params"`
}

// Task Statuses
func (q *Queries) CreateTaskStatus(ctx context.Context, arg CreateTaskStatusParams) (LidarTaskStatus, error) {
	row := q.db.QueryRowContext(ctx, createTaskStatus,
		arg.ID,
		arg.Subject,
		arg.Status,
		arg.TaskParams,
	)
	var i LidarTaskStatus
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Status,
		&i.TaskParams,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getTaskStatusByID = `-- name: GetTaskStatusByID :one
SELECT id, subject, status, task_params, error_message, created_at, updated_at, started_at, finished_at FROM lidar.task_statuses WHERE id = $1
`

func (q *Queries) GetTaskStatusByID(ctx context.Context, id uuid.UUID) (LidarTaskStatus, error) {
	row := q.db.QueryRowContext(ctx, getTaskStatusByID, id)
	var i LidarTaskStatus
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Status,
		&i.TaskParams,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listTaskStatuses = `-- name: ListTaskStatuses :many
SELECT id, subject, status, task_params, error_message, created_at, updated_at, started_at, finished_at FROM lidar.task_statuses ORDER BY created_at DESC
`

func (q *Queries) ListTaskStatuses(ctx context.Context) ([]LidarTaskStatus, error) {
	rows, err := q.db.QueryContext(ctx, listTaskStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LidarTaskStatus
	for rows.Next() {
		var i LidarTaskStatus
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Status,
			&i.TaskParams,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE lidar.task_statuses SET
    status             = $2,
    error_message      = $3,
    updated_at         = now(),
    started_at         = CASE
                            WHEN $2 = 'processing' AND started_at IS NULL THEN now()
                            ELSE started_at
                         END,
    finished_at        = CASE
                            WHEN $2 IN ('completed', 'failed') AND finished_at IS NULL THEN now()
                            ELSE finished_at
                         END
WHERE id = $1
`

type UpdateTaskStatusParams struct {
	ID           uuid.UUID      `json:"id"`
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
